# Generated by Django 3.2.4 on 2026-10-01 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pergunta', models.TextField(max_length=500)),
                ('nivel', models.IntegerField(choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil')], default=1)),
                ('pontuacao', models.IntegerField(default=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniquiz.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('correta', models.BooleanField(default=False)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniquiz.pergunta')),
            ],
        ),
    ]
