# Generated by Django 3.2.4 on 2026-10-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniquiz', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='credencial',
            field=models.IntegerField(choices=[(1, 'Aluno'), (2, 'Professor')], default=1),
        ),
    ]
